'use strict';
const PRODUCTS = [
 {id:'cbc',name:'Общий анализ крови',desc:'С лейкоцитарной формулой',price:790,group:'blood',days:'1 день'},
 {id:'ferritin',name:'Ферритин',desc:'Запасы железа в организме',price:850,group:'vitamins',days:'1 день'},
 {id:'magnesium',name:'Магний',desc:'Магний в сыворотке крови',price:490,group:'vitamins',days:'1 день'},
 {id:'glucose',name:'Глюкоза',desc:'Глюкоза в венозной крови',price:390,group:'blood',days:'1 день'},
 {id:'biochem',name:'Биохимия крови',desc:'Глюкоза, АЛТ, АСТ, общий белок, креатинин, билирубин',price:1690,group:'checkups',days:'1 день',contains:['glucose','alt','ast','protein','creatinine','bilirubin']},
 {id:'d',name:'Витамин D',desc:'25-OH витамин D',price:1590,group:'vitamins',days:'2 дня'},
 {id:'b12',name:'Витамин B12',desc:'Витамин B12 в крови',price:990,group:'vitamins',days:'1 день'},
 {id:'tsh',name:'ТТГ',desc:'Тиреотропный гормон',price:650,group:'hormones',days:'1 день'},
 {id:'base',name:'Базовые показатели',desc:'Общий анализ крови, ферритин, магний и глюкоза',price:2290,group:'checkups',days:'1 день',contains:['cbc','ferritin','magnesium','glucose']},
 {id:'alt',name:'АЛТ',desc:'Аланинаминотрансфераза',price:290,group:'blood',days:'1 день'},
 {id:'ast',name:'АСТ',desc:'Аспартатаминотрансфераза',price:290,group:'blood',days:'1 день'}
];
const INITIAL=['cbc','ferritin','magnesium','glucose'];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const word=(n,forms)=>forms[n%10===1&&n%100!==11?0:n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?1:2];
const number=n=>new Intl.NumberFormat('ru-RU').format(n);
const product=id=>PRODUCTS.find(p=>p.id===id);
const sum=ids=>ids.reduce((a,id)=>a+(product(id)?.price||0),0);
const plural=n=>n%10===1&&n%100!==11?'позиция':n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?'позиции':'позиций';
const SEED=[{id:'example-1',title:'Базовый набор',author:'Анна Королёва',comment:'Собрала для вас список анализов по итогам нашей встречи. Если захотите изменить состав, напишите мне — обсудим.',items:[...INITIAL],uses:8,points:1008},{id:'example-2',title:'Перед следующей встречей',author:'Анна Королёва',comment:'Результаты обсудим на следующей встрече.',items:['cbc','biochem','ferritin'],uses:4,points:666}];
let state;
try{state=JSON.parse(localStorage.getItem('analyses-demo-v1'));}catch{}
if(!state||!Array.isArray(state.cart)||!Array.isArray(state.saved))state={cart:[...INITIAL],saved:structuredClone(SEED)};
state.cart=state.cart.filter(id=>product(id));
state.saved=state.saved.filter(s=>s&&typeof s.id==='string'&&Array.isArray(s.items));
let category='all',query='',recipient=null,recipientCart=[],activeSharedHash='',lastCreated=null,order=null,toastTimer;
function persist(){try{localStorage.setItem('analyses-demo-v1',JSON.stringify(state));}catch{toast('Браузер не сохранил данные. Они доступны до закрытия страницы.');}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function encode(data){return btoa(String.fromCharCode(...new TextEncoder().encode(JSON.stringify(data)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function decode(s){if(s.length>16000)throw Error('Ссылка слишком длинная');const value=JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0))));if(!value||typeof value.id!=='string'||value.id.length>100||typeof value.title!=='string'||value.title.length>80||typeof value.author!=='string'||value.author.length>70||typeof value.comment!=='string'||value.comment.length>600||!Array.isArray(value.items)||!value.items.length||value.items.length>PRODUCTS.length||value.items.some(id=>!product(id)))throw Error('Неверная ссылка');value.items=[...new Set(value.items)];return value;}
function payload(s){return {id:s.id,title:s.title,author:s.author,comment:s.comment,items:[...s.items]};}
function link(s){return location.href.split('#')[0]+'#r/'+encode(payload(s));}
function navigate(route){if(location.hash==='#'+route)render();else location.hash=route;}
function recipientMode(){return !!recipient&&['recipient','recipient-catalog','checkout','complete'].includes(routeName());}
function routeName(){const hash=location.hash.slice(1);return hash.startsWith('r/')?'recipient':hash||'catalog';}
function currentCart(){return recipientMode()?recipientCart:state.cart;}
function syncHeader(){const mode=recipientMode();$('nav').classList.toggle('recipient-nav',mode);$('#cart-count').textContent=state.cart.length;document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('current',a.dataset.nav===routeName()));$('.brand').href=mode?'#r/'+activeSharedHash:'#catalog';}
function row(p,cart,remove=false){const selected=cart.includes(p.id);return `<div class="analysis-row"><div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.desc)}</p><span class="meta">${p.days}${p.contains?' · '+p.contains.length+' '+(p.contains.length===4?'показателя':'показателей'):''}</span></div><strong>${money(p.price)}</strong><button class="round ${remove?'remove':selected?'selected':''}" data-action="toggle" data-id="${p.id}" aria-label="${remove||selected?'Убрать':'Добавить'} ${esc(p.name)}" ${remove?'':`aria-pressed="${selected}"`}>${remove?'×':selected?'✓':'+'}</button></div>`;}
function breadcrumb(label){return `<div class="breadcrumb"><a href="#catalog">Анализы</a> / ${label}</div>`;}
function referral(){return `<div class="referral-note"><span class="plus-badge">5%</span><div><strong>Рекомендуйте и получайте баллы</strong><p>После сдачи по вашей ссылке — 5% баллами Плюса от итоговой стоимости анализов.</p></div></div>`;}
function summary(cart,kind){const total=sum(cart),recv=kind==='recipient';return `<aside class="summary ${kind==='catalog'?'summary-catalog':''}"><span class="eyebrow">${recv?'ВАША КОРЗИНА':'ВЫ ВЫБРАЛИ'}</span><h2>${cart.length} ${plural(cart.length)}</h2><p class="muted">${recv?'Можно изменить состав и обсудить его с автором.':'Сохраните набор и отправьте его тем, кому рекомендуете сдать анализы.'}</p>${kind==='catalog'?`<div class="selected-names">${cart.map(id=>`<span>${esc(product(id).name)}</span>`).join('')}</div>`:''}<div class="total"><span>Итого</span><strong>${money(total)}</strong></div>${recv?`<button class="button primary" data-action="checkout" ${!cart.length?'disabled':''}>Перейти к оформлению</button><p class="tiny">Цены в прототипе — пример. Оплаты и записи не будет.</p>`:kind==='catalog'?`<a class="button primary" href="#cart">Перейти в корзину</a>${referral()}`:`<button class="button primary" data-action="recommend" ${!cart.length?'disabled':''}>Порекомендовать корзину</button><button class="button outline" data-action="recommend" ${!cart.length?'disabled':''}>Сохранить набор</button>${referral()}`}</aside>`;}
function catalog(){const recv=recipientMode(),cart=currentCart();return `${recv?`<a class="back" href="#r/${activeSharedHash}">← К рекомендации</a>`:breadcrumb('Каталог')}<div class="page-heading"><div><h1>${recv?'Добавьте нужные анализы':'Что хотите проверить?'}</h1><p class="muted">${recv?'Изменения сохранятся только в вашей корзине.':'Выберите анализы для себя или соберите набор для другого человека.'}</p></div></div><div class="workspace"><section><div class="search-wrap"><span aria-hidden="true">⌕</span><input id="search" aria-label="Поиск анализов" placeholder="Название анализа или показателя" value="${esc(query)}"><button class="text-button" data-action="clear-search" aria-label="Очистить поиск">×</button></div><div class="chips" aria-label="Категории">${[['all','Все анализы'],['checkups','Чекапы'],['vitamins','Витамины и минералы'],['hormones','Гормоны'],['blood','Исследования крови']].map(([id,name])=>`<button class="chip ${id===category?'active':''}" data-action="filter" data-id="${id}" aria-pressed="${id===category}">${name}</button>`).join('')}</div><section class="panel"><div class="panel-title"><h2>${category==='checkups'?'Чекапы':'Анализы'}</h2><span class="muted"></span></div><div id="catalog-list">${catalogRows(cart)}</div></section></section>${recv?summary(cart,'recipient'):summary(cart,'catalog')}</div><a class="mobile-basket" href="${recv?'#r/'+activeSharedHash:'#cart'}"><span>${recv?'К рекомендации':'Корзина'} · ${cart.length}</span><span>${money(sum(cart))} →</span></a>`;}
function catalogRows(cart){const matches=PRODUCTS.filter(p=>(category==='all'||p.group===category)&&`${p.name} ${p.desc}`.toLowerCase().includes(query.toLowerCase().trim()));return matches.length?matches.map(p=>row(p,cart)).join(''):`<div class="empty"><h2>Ничего не нашли</h2><p class="muted">Попробуйте другое название или выберите все анализы.</p><button class="button" data-action="reset-filter">Сбросить поиск</button></div>`;}
function notices(cart){const duplicates=[...new Set(cart.flatMap(id=>(product(id).contains||[]).filter(x=>cart.includes(x))))];let html='';if(cart.includes('base')&&cart.includes('biochem'))html+='<div class="notice"><span aria-hidden="true">↔</span><div><strong>Глюкоза входит в оба чекапа</strong><p>В наборах «Базовые показатели» и «Биохимия крови» есть общий анализ. Проверьте состав перед оформлением: удаление целого чекапа уберёт и другие показатели.</p></div></div>';if(duplicates.length)html+=`<div class="notice"><span aria-hidden="true">↔</span><div><strong>Есть повторяющиеся анализы</strong><p>${duplicates.map(id=>esc(product(id).name)).join(', ')} уже ${duplicates.length===1?'входит':'входят'} в выбранный чекап. Можно убрать отдельные позиции и сэкономить ${money(sum(duplicates))}.</p><button class="text-button" data-action="dedupe">Убрать дубли · −${money(sum(duplicates))}</button></div></div>`;if(INITIAL.every(id=>cart.includes(id))&&!cart.some(id=>product(id).contains))html+=`<div class="notice success"><span aria-hidden="true">↓</span><div><strong>Тот же состав — на 230 ₽ дешевле</strong><p>ОАК, ферритин, магний и глюкоза есть в чекапе «Базовые показатели». Все четыре анализа сохранятся.</p><button class="text-button" data-action="bundle">Заменить четыре анализа чекапом</button></div></div>`;return html;}
function cartPage(recv=false){const cart=recv?recipientCart:state.cart;return `${recv?'':breadcrumb('Корзина')}${recv?`<section class="recipient-intro"><span class="eyebrow">ВАМ РЕКОМЕНДОВАЛИ</span><div class="author"><span class="author-dot"></span>${esc(recipient.author)}</div><h1>${esc(recipient.title)}</h1>${recipient.comment?`<p class="comment">${esc(recipient.comment)}</p>`:''}<p class="tiny">Имя и комментарий указаны автором набора.</p></section>`:`<div class="page-heading"><div><h1>Ваша корзина</h1><p class="muted">Всё нужное в одном наборе. Сохраните его или поделитесь рекомендацией.</p></div><a href="#catalog" class="button outline">+ Добавить анализы</a></div>`}<div class="workspace"><section>${cart.length?`<section class="panel"><div class="panel-title"><h2>${recv?'Состав рекомендации':'Выбранные анализы'}</h2><span class="muted">${cart.length} ${plural(cart.length)}</span></div>${cart.map(id=>row(product(id),cart,true)).join('')}<div class="list-bottom"><a class="text-button" href="${recv?'#recipient-catalog':'#catalog'}">+ Добавить анализы</a>${recv?`<button class="text-button" data-action="restore">Вернуть исходный состав</button>`:''}</div></section>${notices(cart)}`:`<section class="panel empty"><div class="empty-symbol">＋</div><h2>В корзине пока пусто</h2><p class="muted">Выберите анализы или готовый чекап.</p><a class="button primary" href="${recv?'#recipient-catalog':'#catalog'}">Открыть каталог</a>${recv?'<p><button class="text-button section-gap" data-action="restore">Вернуть исходный состав</button></p>':''}</section>`}${recv?'<p class="tiny section-gap">Вы можете изменить состав. При необходимости обсудите изменения с автором рекомендации в привычном чате.</p>':'<p class="tiny section-gap">Получатель сможет изменить свою корзину. Ваш сохранённый набор останется прежним.</p>'}</section>${summary(cart,recv?'recipient':'cart')}</div>`;}
function recommendationModal(prefill){const cart=[...state.cart];if(!cart.length)return;const modal=$('#modal');modal.innerHTML=`<form id="recommend-form"><div class="modal-head"><h2>Поделиться набором</h2><button type="button" class="round" data-action="close" aria-label="Закрыть">×</button></div><p class="muted">Сохраните подборку — её можно отправлять снова.</p><label for="set-title">Название набора</label><input class="field" id="set-title" name="title" maxlength="80" required placeholder="Например, перед следующей встречей" value="${esc(prefill?.title||'')}"><label for="set-author">Ваше имя для получателя</label><input class="field" id="set-author" name="author" maxlength="70" required placeholder="Анна Королёва" value="${esc(prefill?.author||'Анна Королёва')}"><label for="set-comment">Комментарий <span class="muted">· необязательно</span></label><textarea id="set-comment" name="comment" maxlength="600" placeholder="Что важно знать перед сдачей или что обсудить с вами">${esc(prefill?.comment||'')}</textarea><p class="tiny">Имя, комментарий и состав увидит каждый, у кого есть ссылка.</p><div class="line-item section-gap"><span>${cart.length} ${plural(cart.length)}</span><strong>${money(sum(cart))}</strong></div><button class="button primary" type="submit">Сохранить и получить ссылку</button><p class="tiny">После сдачи по ссылке вам вернётся 5% баллами Плюса.</p></form>`;modal.showModal();$('#recommend-form').addEventListener('submit',e=>{e.preventDefault();const form=new FormData(e.target),title=String(form.get('title')).trim(),author=String(form.get('author')).trim();if(!title||!author){toast('Укажите название и имя автора');return;}const item={id:crypto.randomUUID?.()||String(Date.now()),title,author,comment:String(form.get('comment')).trim(),items:cart,uses:0,points:0};state.saved.unshift(item);persist();lastCreated=item;modal.close();navigate('shared');});}
function sharedPage(){const item=lastCreated||state.saved[0];if(!item)return savedPage();return `<a class="back" href="#cart">← К корзине</a><section class="center-page"><div class="success-mark">✓</div><h1>Рекомендация готова</h1><p class="muted">Ссылка многоразовая: отправьте её одному человеку, нескольким клиентам или опубликуйте в своём канале.</p><div class="form-card section-gap"><span class="eyebrow">СОХРАНЁННЫЙ НАБОР</span><h2 class="section-gap">${esc(item.title)}</h2><p class="muted section-gap">${item.items.length} ${plural(item.items.length)} · ${money(sum(item.items))}</p><div class="link-row"><input class="field" readonly aria-label="Ссылка на рекомендацию" value="${esc(link(item))}"></div><button class="button primary" data-action="copy" data-id="${item.id}">Скопировать ссылку</button><a class="button outline" href="${esc(link(item))}">Посмотреть глазами получателя ↗</a>${referral()}</div><p class="tiny section-gap">Набор доступен в разделе «Мои рекомендации». В этой демоверсии сохранение работает в вашем браузере.</p><a class="button section-gap" href="#saved">Мои рекомендации →</a></section>`;}
function savedPage(){const uses=state.saved.reduce((a,s)=>a+(s.uses||0),0),points=state.saved.reduce((a,s)=>a+(s.points||0),0);return `${breadcrumb('Мои рекомендации')}<div class="page-heading"><div><h1>Мои рекомендации</h1><p class="muted">Ваши наборы анализов, которыми можно делиться снова.</p></div><a class="button primary" href="#catalog">+ Собрать набор</a></div><div class="stats"><div class="stat reward"><strong>${number(points)} <span style="font-size:20px">${word(points,['балл','балла','баллов'])}</span></strong><p>Начислено баллами Плюса</p></div><div class="stat"><strong>${uses}</strong><p>Сдач по вашим ссылкам</p></div><div class="stat"><strong>${state.saved.length}</strong><p>Сохранённых наборов</p></div></div><div class="panel-title"><h2>Сохранённые наборы</h2><span class="muted">Демонстрационные данные</span></div>${state.saved.map(s=>`<article class="saved-card"><div><h2>${esc(s.title)}</h2><p class="muted">${s.items.length} ${plural(s.items.length)} · ${money(sum(s.items))}</p><p class="muted">${s.items.map(id=>esc(product(id)?.name||'')).join(' · ')}</p><div class="saved-metrics"><span><strong>${s.uses||0}</strong> ${word(s.uses||0,['сдача','сдачи','сдач'])} по ссылке</span><span class="reward-amount"><strong>+${number(s.points||0)}</strong> ${word(s.points||0,['балл','балла','баллов'])} Плюса</span><button class="text-button" data-action="rename" data-id="${s.id}">Переименовать</button></div></div><div class="saved-actions"><button class="button outline" data-action="use-set" data-id="${s.id}">В корзину</button><button class="button primary" data-action="copy" data-id="${s.id}">Поделиться</button></div></article>`).join('')}<div class="notice section-gap"><span class="plus-badge">5%</span><div><strong>Баллы приходят после сдачи анализов</strong><p>Вознаграждение рассчитывается от итоговой корзины получателя, даже если он изменил её состав.</p></div></div><p class="tiny">Демоверсия: наборы и изменения статистики хранятся только в этом браузере. Ссылка переносит состав набора, но не синхронизирует реальные заказы.</p>`;}
function checkoutPage(){if(!recipient||!recipientCart.length){navigate(recipient?'r/'+activeSharedHash:'cart');return '';}return `<a class="back" href="#r/${activeSharedHash}">← К рекомендации</a><div class="page-heading"><div><h1>Оформление</h1><p class="muted">Проверьте состав перед следующим шагом.</p></div></div><div class="workspace"><section><section class="panel"><div class="panel-title"><h2>Ваш заказ</h2><span class="muted">${recipientCart.length} ${plural(recipientCart.length)}</span></div>${recipientCart.map(id=>`<div class="line-item payment-breakdown"><span>${esc(product(id).name)}</span><strong>${money(product(id).price)}</strong></div>`).join('')}</section><div class="checkout-note"><strong>Здесь начинается обычное оформление заказа</strong><p class="muted" style="margin-top:8px">Выбор лаборатории, даты и оплата остаются в B2C-сценарии. Для проверки новой функции пройдите демонстрационную сдачу.</p></div></section><aside class="summary"><span class="eyebrow">ДЕМОНСТРАЦИОННЫЙ ЗАКАЗ</span><div class="total"><span>Итого</span><strong>${money(sum(recipientCart))}</strong></div><button class="button primary" data-action="complete">Пройти демосдачу</button><p class="tiny">Это действие только завершит сценарий прототипа. Записи, оплаты и медицинских результатов не будет.</p></aside></div>`;}
function completePage(){if(!order)return `<div class="empty"><h1>Заказ не найден</h1><a class="button" href="#catalog">В каталог</a></div>`;return `<section class="center-page"><div class="success-mark">✓</div><h1>Сценарий пройден</h1><p class="muted">В демоверсии вы сдали анализы из своей итоговой корзины.</p><div class="form-card section-gap"><span class="eyebrow">ИТОГОВЫЙ СОСТАВ</span>${order.items.map(id=>`<div class="line-item section-gap"><span>${esc(product(id).name)}</span><strong>${money(product(id).price)}</strong></div>`).join('')}<div class="total"><span>Итого</span><strong>${money(order.total)}</strong></div></div><div class="checkout-note"><strong>Для показа прототипа</strong><p class="muted" style="margin-top:8px">Теперь можно вернуться на сторону автора и посмотреть статистику рекомендаций.</p><a class="button dark section-gap" href="#saved">Перейти к автору →</a></div></section>`;}
function invalidLink(){return `<section class="empty"><h1>Не удалось открыть рекомендацию</h1><p class="muted section-gap">Ссылка неполная или повреждена. Попросите автора отправить её ещё раз.</p><a class="button primary" href="#catalog">Открыть каталог</a></section>`;}
function render(){const route=routeName();if(route==='recipient'){try{const raw=location.hash.slice(3);if(raw!==activeSharedHash){recipient=decode(raw);recipientCart=[...recipient.items];activeSharedHash=raw;order=null;}}catch{$('#app').innerHTML=invalidLink();return;}}if(['recipient-catalog','checkout'].includes(route)&&!recipient){navigate('catalog');return;}syncHeader();const pages={catalog,cart:()=>cartPage(false),recipient:()=>cartPage(true),'recipient-catalog':catalog,shared:sharedPage,saved:savedPage,checkout:checkoutPage,complete:completePage};$('#app').innerHTML=(pages[route]||catalog)();$('#app').classList.remove('route-enter');void $('#app').offsetWidth;$('#app').classList.add('route-enter');if($('#search'))$('#search').addEventListener('input',e=>{query=e.target.value;$('#catalog-list').innerHTML=catalogRows(currentCart());});}
function toggle(id){if(!product(id))return;const cart=currentCart(),at=cart.indexOf(id);at>=0?cart.splice(at,1):cart.push(id);persist();const y=window.scrollY;render();window.scrollTo(0,y);toast(at>=0?'Анализ убран из корзины':'Анализ добавлен');}
async function copy(s){try{await navigator.clipboard.writeText(link(s));toast('Ссылка скопирована — можно отправлять');}catch{const modal=$('#modal');modal.innerHTML=`<div class="modal-head"><h2>Ссылка на набор</h2><button class="round" data-action="close" aria-label="Закрыть">×</button></div><p class="muted">Выделите и скопируйте ссылку.</p><input class="field section-gap" readonly value="${esc(link(s))}">`;modal.showModal();modal.querySelector('input').select();}}
function rename(s){const modal=$('#modal');modal.innerHTML=`<form id="rename-form"><div class="modal-head"><h2>Название набора</h2><button type="button" class="round" data-action="close" aria-label="Закрыть">×</button></div><label for="rename-title">Новое название</label><input class="field" id="rename-title" name="title" value="${esc(s.title)}" maxlength="80" required><p class="tiny">Название обновится в вашем списке и в новой копии ссылки. Ранее отправленная ссылка останется прежней.</p><button type="submit" class="button primary">Сохранить название</button></form>`;modal.showModal();$('#rename-form').onsubmit=e=>{e.preventDefault();const title=new FormData(e.target).get('title').trim();if(!title)return;s.title=title;persist();modal.close();render();toast('Название сохранено');};}
document.addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(!button)return;const action=button.dataset.action,id=button.dataset.id,cart=currentCart(),saved=state.saved.find(s=>s.id===id);if(action==='toggle')toggle(id);if(action==='filter'){category=id;render();}if(action==='clear-search'){query='';render();$('#search')?.focus();}if(action==='reset-filter'){query='';category='all';render();}if(action==='recommend')recommendationModal();if(action==='close')$('#modal').close();if(action==='copy'&&saved)copy(saved);if(action==='rename'&&saved)rename(saved);if(action==='use-set'&&saved){state.cart=[...saved.items];persist();navigate('cart');toast('Набор добавлен в отдельную корзину');}if(action==='checkout'){order=null;navigate('checkout');}if(action==='restore'){recipientCart=[...recipient.items];render();toast('Исходный состав восстановлен');}if(action==='dedupe'){const dup=new Set(cart.flatMap(id=>(product(id).contains||[]).filter(x=>cart.includes(x))));const next=cart.filter(id=>!dup.has(id));if(recipientMode())recipientCart=next;else state.cart=next;persist();render();toast('Дубли убраны, сумма пересчитана');}if(action==='bundle'){const next=cart.filter(id=>!INITIAL.includes(id));next.push('base');if(recipientMode())recipientCart=next;else state.cart=next;persist();render();toast('Те же четыре анализа — в чекапе на 230 ₽ дешевле');}if(action==='complete'&&recipient&&!order){const total=sum(recipientCart);order={items:[...recipientCart],total};const original=state.saved.find(s=>s.id===recipient.id);if(original){original.uses=(original.uses||0)+1;original.points=(original.points||0)+Math.floor(total*.05);persist();}navigate('complete');}});
$('#demo-reset').addEventListener('click',()=>{const modal=$('#modal');modal.innerHTML=`<div class="modal-head"><h2>Начать показ заново?</h2><button class="round" data-action="close" aria-label="Закрыть">×</button></div><p class="muted">Созданные в этом браузере наборы и демосдачи будут сброшены. Вернутся исходная корзина и примеры.</p><div class="dialog-actions"><button class="button" data-action="close">Отмена</button><button class="button primary" id="confirm-reset">Начать заново</button></div>`;modal.showModal();$('#confirm-reset').onclick=()=>{state={cart:[...INITIAL],saved:structuredClone(SEED)};recipient=null;recipientCart=[];activeSharedHash='';lastCreated=null;order=null;query='';category='all';persist();modal.close();navigate('catalog');toast('Готово к новому показу');};});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
render();
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'read_analysis_cart',description:'Read the current prototype cart and total.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return {items:currentCart().map(id=>({id,name:product(id).name,price:product(id).price})),total:sum(currentCart())};}},{name:'set_analysis_cart',description:'Replace the current prototype cart with selected catalog IDs. Does not create a recommendation or order.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string'},maxItems:PRODUCTS.length}},required:['ids'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>k!=='ids')||!Array.isArray(input.ids)||input.ids.length>PRODUCTS.length||input.ids.some(id=>typeof id!=='string'||!product(id)))throw Error('Use valid catalog IDs');const ids=[...new Set(input.ids)];if(recipientMode())recipientCart=ids;else state.cart=ids;persist();render();return {items:ids,total:sum(ids)};}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}
